# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: Run maven script
      uses: xlui/action-maven-cli/jdk11@master
      id: test
      with:
        lifecycle: 'clean package test'
